
CREATE TABLE IF NOT EXISTS GD_ACCOUNT_ADT LIKE WHITE_WINE_QUALITY;
CREATE TABLE IF NOT EXISTS GD_ALLERGY_INTOLERANCE_ADT LIKE WHITE_WINE_QUALITY;
CREATE TABLE IF NOT EXISTS GD_BUNDLE_RESOURCE_METADATA_ADT LIKE WHITE_WINE_QUALITY;
CREATE TABLE IF NOT EXISTS GD_CONDITION_ADT LIKE WHITE_WINE_QUALITY;

ALTER TABLE GD_ACCOUNT_ADT ADD GD_MD5_VALUE VARCHAR(16777216), GD_INGESTION_TIME VARCHAR(16777216);
ALTER TABLE GD_ALLERGY_INTOLERANCE_ADT ADD GD_MD5_VALUE VARCHAR(16777216), GD_INGESTION_TIME VARCHAR(16777216);
ALTER TABLE GD_BUNDLE_RESOURCE_METADATA_ADT ADD GD_MD5_VALUE VARCHAR(16777216), GD_INGESTION_TIME VARCHAR(16777216);
ALTER TABLE GD_CONDITION_ADT ADD GD_MD5_VALUE VARCHAR(16777216), GD_INGESTION_TIME VARCHAR(16777216);