name: python-connector

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.10.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.10.x

      - name: Installing dependencies
        run: |
          echo "Installing dependencies"
          pip install snowflake-connector-python

      - name: Print wine quality column names
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
        run : |
          echo "printing wine quality table column names"
          python3 $GITHUB_WORKSPACE/wine-quality-scripts/get_column_names.py
        
      - name: Copy data from WHITE_WINE_QUALITY into GD tables and generate MD5 checksum
        run: 
          echo "copying data from WHITE_WINE_QUALITY into GD tables"
          python3 $GITHUB_WORKSPACE/wine-quality-scripts/copy_data_generate_md5.py